### ISSUE TITLE
Firefox image stretch

### ISSUE THREAD

**Issue by gduck** [drostehk/drostehk.github.io#10]
Firefox can't use max-height & max-width like everyone else when using with flex. If position is absolute then the images' aspect ratio corrects but they look worse imho.

I haven't found a workable solution yet. 

![screen shot 2017-08-25 at 2 18 32 pm](https://user-images.githubusercontent.com/9581715/29701804-9fe7e160-89a0-11e7-8c37-695a52c64029.png)

**Comment by tijptjik** [comment]
I'll try adding `align-items: center;` to `#home #clients > .grid .row > .column > div`. This should do the trick. Also setting `max-width `to `75% `for `#home #clients > .grid img`.
